### ISSUE TITLE
PyQt5 version is uninstallable

### ISSUE THREAD

**Issue by efjerb** [manumerous/visual_dataframe_selector#20] opened 2023-09-19 08:02 UTC
Hi,

Just tried to install the package. It appears that there is a problem with PyQt5 v. 5.14.0, where the dependencies are specified incorrectly. I get the same error as [here](https://stackoverflow.com/questions/70616293/hello-how-to-fix-this-errors-im-trying-to-install-pyqt5-tools-using-pip-insta) when installing. I suggest to update to PyQt v. 5.14.1 or the most recent version to correct this issue.

**Comment by manumerous** [comment] 2023-09-20 05:32
Thanks a lot for reporting this! Yes it seems to be an issue with pyqt itself. Feel free to open a PR and address the issue. Else I will do so as soon as I find time.

**Comment by manumerous** [comment] 2023-09-20 06:37
This is addressed in PR #21

**Comment by saiyalamarty** [comment] 2023-09-20 17:21
I am getting an error on v1.0.1 as well. Unable to install the locked version of PyQt5. But I was able to pip install latest version of PyQt5.

I was successful in installing vpselector by making the PyQt5 requirement relaxed.

**Comment by manumerous** [comment] 2023-09-20 18:27
Thanks for reporting this. There is no reason for not specifying a minimum version. I must have overlooked that. Just out of curiosity, what operating system are you running on? On my local machine I can not reproduce these difficulties. 

A fix is on the way though.

**Comment by manumerous** [comment] 2023-09-21 07:07
This issue should have been addressed in PR #22. Let me know if that fixes the issue for you.

**Comment by saiyalamarty** [comment] 2023-09-21 19:19
I am using windows, python 3.11

v1.0.2 is working. Successfully installed PyQt5!! Thank you!

**Comment by manumerous** [comment] 2023-09-21 19:46
Thank a lot for your contribution to this project! It is much appreciated!

**Closed as completed by manumerous** 2023-09-21 19:46 UTC
